# Generated by Django 3.0.5 on 2023-06-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0002_auto_20230615_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='waste_producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_app.Customer'),
        ),
    ]
