# Generated by Django 3.0.5 on 2023-06-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0002_auto_20230614_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
