# Generated by Django 3.0.5 on 2023-06-15 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms_app', '0003_auto_20230615_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='waste_producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
